[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"

# Function redirects - this is the most important redirect
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# API redirects - this is a convenience redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Serve images directly
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
